stages:
  - test

test:
  stage: test
  image: python:3.13-alpine
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "Running Test"
    - apk add gcc python3-dev musl-dev linux-headers
    - pip install hatch
    - hatch shell
    - hatch test