stages:
  - test
  - coverage

test:
  stage: test
  image: python:3.13-alpine
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "Running Test"
    - apk add gcc python3-dev musl-dev linux-headers
    - pip install hatch
    - hatch shell
    - hatch test

# Étape de couverture
coverage:
  stage: coverage
  image: python:3.13-alpine
  script:
    - echo "Collecting Code Coverage"
    - pip install pytest-cov
    - pytest --cov=src --cov-report=lcov tests/
    - cat coverage.lcov
  artifacts:
    paths:
      - coverage.lcov
    expire_in: 1 hour

coverage_report:
  stage: coverage
  script:
    - echo "Uploading Code Coverage Report"
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+)%/'
