stages:
  - test

test:
  stage: test
  image: python:3.13-alpine
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "Running Test"
    - pip install -r hatch
    - hatch shell
    - hatch test

# modif for commit 5